---
title: "Advent of Code 2021"
author: "Kyle Harris"
date: "`r Sys.Date()`"
output:
  rmdformats::downcute:
    self_contained: true
    default_style: "dark"
    includes:
      in_header: header.html
---

```{r setup, include = FALSE}
## Global options
knitrhooks::output_max_height()
knitr::opts_chunk$set(
  cache = TRUE,
  output_max_height = "300px"
)
```

```{css, echo = FALSE}
pre:not(.r) {
  margin-bottom: 50px;
}
```

# Packages

```{r, message = FALSE, warning = FALSE}
library(tidyverse)
library(zoo)
library(details)
```

Globally set `show_col_types = FALSE`.

```{r}
read_tsv <- partial(read_tsv, show_col_types = FALSE)
```

# Day 1

## Setup

```{r}
d <- "data/01.txt" |>
  read_lines() |>
  as.numeric() |>
  enframe(value = "x")

d
```

## Part 1

```{r}
d_1 <-
  d |>
  mutate(
    diff = x - lag(x)
  ) |>
  summarize(
    x = sum(diff > 0, na.rm = TRUE)
  )

d_1
```

## Part 2

```{r}
d_2 <- d

d_2$y <- rollsum(d$x, 3, align = "left", fill = 0)

d_2
```

```{r}
d_2 |>
  mutate(
    diff = y - lag(y)
  ) |>
  summarize(
    y = sum(diff > 0, na.rm = TRUE)
  )
```

# Day 2

## Setup

```{r}
d_init <- read_tsv(
  file = "data/02.txt",
  col_names = FALSE
)

d <-
  d_init |>
  separate(
    col = X1,
    into = c("position", "unit"),
    convert = TRUE
  ) |>
  mutate(
    unit = if_else(
      condition = position == "up",
      true = unit * -1L,
      false = unit
    ),
    group = if_else(
      condition = position == "forward",
      true = "x",
      false = "y"
    )
  )

d
```

## Part 1

```{r}
d |>
  group_by(group) |>
  summarize(
    units = sum(unit)
  ) |>
  pull(units) |>
  prod()
```

## Part 2

```{r}
d |>
  mutate(
    aim = cumsum(ifelse(group == "y", unit, 0))
  ) |>
  filter(group == "x") |>
  summarize(
    x = sum(unit),
    y = sum(unit * aim),
    solution = x * y
  )
```

# Day 3

## Setup

```{r}
d_init <-
  read_tsv(
    file = "data/03.txt",
    col_names = FALSE
  )

n_cols <- nchar(d_init$X1[1])

col_names <- paste0(
  "col_",
  str_pad(0:n_cols, width = 2, pad = 0)
)

col_names
```


```{r}
d <-
  d_init |>
  separate(
    col = X1,
    into = col_names,
    sep = "",
    convert = TRUE
  ) |>
  select(-1)

d
```

## Part 1

```{r}
d_1 <-
  d |>
  pivot_longer(
    cols = everything()
  ) |>
  count(name, value) |>
  group_by(name) |>
  summarize(
    gamma = value[which.max(n)],
    epsilon = value[which.min(n)]
  )

d_1
```

```{r}
gamma <-
  paste0(d_1$gamma, collapse = "") |>
  strtoi(base = 2)

epsilon <-
  paste0(d_1$epsilon, collapse = "") |>
  strtoi(base = 2)

gamma * epsilon
```

## Part 2

### Reproduce Example

Recreating the work and results in the example help build the solution.

```{r}
example_d_init <- c(
  "00100", "11110", "10110",
  "10111", "10101", "01111",
  "00111", "11100", "10000",
  "11001", "00010", "01010"
) |>
  enframe(value = "X1")

example_n_cols <- nchar(example_d_init$X1[1])

example_col_names <- paste0(
  "col_",
  str_pad(0:example_n_cols, width = 2, pad = 0)
)

example_d <-
  example_d_init |>
  separate(
    col = X1,
    into = example_col_names,
    sep = "",
    convert = TRUE
  ) |>
  select(-(1:2))

example_d
```


```{r}
i <- 1
i_max <- ncol(example_d)
d_oxygen <- d_co2 <- example_d

while (i <= i_max) {
  ref_col <- rlang::sym(example_col_names[i + 1])
  
  d_oxygen_count <-
    d_oxygen |>
    add_count({{ ref_col }}, name = "n")
  
  d_co2_count <-
    d_co2 |>
    add_count({{ ref_col }}, name = "n")
  
  if (length(unique(d_oxygen_count$n)) == 1) {
    d_oxygen <-
      d_oxygen_count |>
      filter({{ ref_col }} == 1)
    
    d_co2 <-
      d_co2_count |>
      filter({{ ref_col }} == 0)
    
  } else {
    d_oxygen <-
      d_oxygen_count |>
      filter(n == max(n))
    
    d_co2 <-
      d_co2_count |>
      filter(n == min(n))
  }
  
  i <- i + 1
}
```

```{r}
oxygen <-
  d_oxygen |>
  select(-n) |>
  unite(
    col = binary,
    everything(),
    sep = ""
  ) |>
  mutate(decimal = strtoi(binary, base = 2))

oxygen
```

```{r}
co2 <-
  d_co2 |>
  select(-n) |>
  unite(
    col = binary,
    everything(),
    sep = ""
  ) |>
  mutate(decimal = strtoi(binary, base = 2))

co2
```

```{r}
## Matches!
oxygen$decimal * co2$decimal
```

### Translate example code for solution

```{r}
i <- 1
i_max <- ncol(d)
d_oxygen <- d_co2 <- d

while (i <= i_max) {
  ref_col <- rlang::sym(col_names[i + 1])
  
  d_oxygen_count <-
    d_oxygen |>
    add_count({{ ref_col }}, name = "n")
  
  d_co2_count <-
    d_co2 |>
    add_count({{ ref_col }}, name = "n")
  
  if (nrow(d_oxygen_count) == 1) {
    ## If there is only one row, do nothing
    d_oxygen <- d_oxygen_count
    
  } else if (length(unique(d_oxygen_count$n)) == 1) {
    ## If all counts are the same, keep the 1's
    d_oxygen <-
      d_oxygen_count |>
      filter({{ ref_col }} == 1)
    
    ## If there are no 1's, do not remove anything
    if (nrow(d_oxygen) == 0) {
      d_oxygen <- d_oxygen_count
    }
    
  } else {
    ## Keep the most common value
    d_oxygen <-
      d_oxygen_count |>
      filter(n == max(n))
  }
  
  if (nrow(d_co2_count) == 1) {
    ## If there is only one row, do nothing
    d_co2 <- d_co2_count
    
  } else if (length(unique(d_co2_count$n)) == 1) {
    ## If all counts are the same, keep the 0's
    d_co2 <-
      d_co2_count |>
      filter({{ ref_col }} == 0)
    
    ## If there are no 0's, do not remove anything
    if (nrow(d_co2) == 0) {
      d_co2 <- d_co2_count
    }
    
  } else {
    ## Keep the least common value
    d_co2 <-
      d_co2_count |>
      filter(n == min(n))
  }
  
  i <- i + 1
}
```

```{r}
oxygen <-
  d_oxygen |>
  select(-n) |>
  unite(
    col = binary,
    everything(),
    sep = ""
  ) |>
  mutate(decimal = strtoi(binary, base = 2))

oxygen
```

```{r}
co2 <-
  d_co2 |>
  select(-n) |>
  unite(
    col = binary,
    everything(),
    sep = ""
  ) |>
  mutate(decimal = strtoi(binary, base = 2))

co2
```

```{r}
oxygen$decimal * co2$decimal
```

# Day 4

## Setup

```{r}
bingo_numbers <- read_lines(
  file = "data/04.txt",
  n_max = 1
) %>% 
  str_split(",") %>% 
  unlist() %>% 
  as.integer()

bingo_numbers
```


```{r}
d_init <- read_tsv(
  file = "data/04.txt",
  skip = 1,
  col_names = FALSE
)

d_init
```


```{r}
(d_rows <- nrow(d_init))

(col_names <- str_c("col_", 1:5))

l_d <-
  d_init %>% 
  separate(
    col = X1,
    into = col_names,
    convert = TRUE
  ) %>% 
  mutate(
    id = sort(rep(1:100, 5))
  ) %>% 
  group_split(id, .keep = FALSE)

l_d[1:3]
```

## Part 1

```{r}
l_d_1 <- l_d
bingo_check <- TRUE
i <- 1
winning_board <- numeric()

while (bingo_check) {
  print(i)
  bingo_call <- bingo_numbers[i]
  
  for (j in seq_along(l_d_1)) {
    ## Update values to 0 that are called
    l_d_1[[j]] <-
      l_d_1[[j]] %>% 
      mutate(
        across(
          .fns = ~ ifelse(
            test = .x == bingo_call,
            yes = 0,
            no = .x
          )
        )
      )
    
    if (any(colSums(l_d_1[[j]]) == 0 | rowSums(l_d_1[[j]]) == 0)) {
      print("Bingo!")
      print(str_c("Winning number was ", bingo_call))
      winning_board <- j
      bingo_check <- FALSE
      break
    }
  }
  
  i <- i + 1
}

winning_board
```

```{r}
l_d_1[[winning_board]]
```

```{r}
(bingo_sum <- sum(l_d_1[[winning_board]]))
```

```{r}
bingo_call * bingo_sum
```

## Part 2

```{r}
l_d_2 <- l_d
bingo_check <- TRUE
i <- 1
winning_board <- numeric()
last_board <- numeric()

while (bingo_check) {
  bingo_call <- bingo_numbers[i]
  
  for (j in seq_along(l_d_2)) {
    ## Update values to 0 that are called
    l_d_2[[j]] <-
      l_d_2[[j]] %>% 
      mutate(
        across(
          .fns = ~ ifelse(
            test = .x == bingo_call,
            yes = 0,
            no = .x
          )
        )
      )
    
    if (any(colSums(l_d_2[[j]]) == 0 | rowSums(l_d_2[[j]]) == 0)) {
      if (!j %in% winning_board) {
        winning_board[length(winning_board) + 1] <- j
      }
    }
    
    if (length(winning_board) == length(l_d_2)) {
      bingo_check <- FALSE
      last_bard <- j
      break
    }
  }
  
  i <- i + 1
}

last_board <- l_d_2[winning_board[length(winning_board)]]

last_board
```

```{r}
(bingo_sum <- sum(unlist(last_board)))
```

```{r}
bingo_call * bingo_sum
```

# Reproducability Receipt

```{details, details.summary = "Time Info", echo = FALSE}
Sys.time()
```

```{details, details.summary = "Repo Info", echo = FALSE}
git2r::repository()
```

```{details, details.summary = "Session Info", echo = FALSE}
sessioninfo::session_info()
```
